general {
    lock_cmd = hyprlock
}

listener {
    timeout = 200
    on-timeout = bash /home/ander/.config/hypr/scripts/screensaver/salvapantallas
}

#listener {
 #   timeout = 153
 #   on-timeout = hyprlock
#}
